# Generated by Django 4.1.6 on 2023-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_order_description_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('women', 'women'), ('Shose', 'Shose'), ('Watch', 'Watch'), ('Bag', 'Bag')], max_length=10, null=True),
        ),
    ]
