# Generated by Django 4.1.6 on 2023-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women'), ('shoes', 'shoes'), ('watch', 'watch'), ('bag', 'bag')], max_length=10, null=True),
        ),
    ]
